# Generated by Django 3.1.4 on 2020-12-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201218_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categoria',
        ),
    ]
