# Generated by Django 3.1.4 on 2020-12-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='denunciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Cuando Publicarlo'),
        ),
    ]
